config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "properties#index"
  resources :properties do
    resources :availabilities
  end

  resources :availabilities, only: [] do
    resources :bookings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/availability.rb
class Availability < ApplicationRecord
  validates_presence_of :manager_name, message: "can't be blank"
  validates_presence_of :scheduled_date, message: "can't be blank"
  validates_presence_of :property
  validate :scheduled_date_is_in_future, on: :create

  belongs_to :property
  has_many :bookings

  scope :future, -> { where("scheduled_date > ?", DateTime.now) }

  def bookable?
    scheduled_date > DateTime.now
  end

  private

  def scheduled_date_is_in_future
    if scheduled_date.present? && scheduled_date < DateTime.now
      errors.add(:scheduled_date, "must be in the future.")
    end
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates_presence_of :availability, message: "must exist"
  validates_presence_of :potential_tenant_name, message: "can't be blank"
  validate :availability_is_bookable, on: :create

  belongs_to :availability

  private

  def availability_is_bookable
    if !availability.bookable?
      errors.add(:availability, "must be bookable.")
    end
  end
end

app/models/property.rb
class Property < ApplicationRecord
  validates_presence_of :name, message: "can't be blank"
  validates_presence_of :address, message: "can't be blank"

  has_many :availabilities, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :find_property
  before_action :find_availability, only: [ :show, :edit, :update, :destroy ]

  def show
    @bookings = @availability.bookings
  end

  def new
    @availability = Availability.new
  end

  def create
    @availability = @property.availabilities.new(availability_params)

    if @availability.save
      flash[:notice] = "Availability successfully created."
      redirect_to property_path(@property)
    else
      flash[:error] = "Failed to create Availability."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @availability.update(availability_params)
      flash[:notice] = "Availability successfully updated."
      redirect_to property_path(@property)
    else
      flash[:error] = "Failed to edit availability."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @availability.destroy
    flash[:notice] = "Availability successfully destroyed."
    redirect_to property_path(@property)
  end

  private

  def find_availability
    @availability = @property.availabilities.find(params[:id])
  end

  def find_property
    @property = Property.find(params[:property_id])
  end

  def availability_params
    params.require(:availability).permit(:manager_name, :scheduled_date)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :find_availability
  before_action :find_property
  before_action :find_booking, except: [ :new, :create ]

  def new
    @booking = Booking.new
  end

  def create
    @booking = @availability.bookings.new(booking_params)
    if @booking.save
      flash[:notice] = "Successfully booked this timeslot."
      redirect_to property_availability_path(@property, @availability)
    else
      flash[:error] = "Failed to book timeslot."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      flash[:notice] = "Successfully updated the booking."
      redirect_to property_availability_path(@property, @availability)
    else
      flash[:error] = "Failed to update the booking."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    flash[:notice] = "Successfully removed the booking."
    redirect_to property_availability_path(@property, @availability)
  end

  private

  def find_availability
    @availability = Availability.find(params[:availability_id])
  end

  def find_property
    @property = @availability.property
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:potential_tenant_name)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :find_property, only: [ :show, :edit, :update, :destroy ]

  def index
    @properties = Property.all
                          .order(created_at: :desc)
                          .eager_load(:availabilities)
                          .page(params[:page])
                          .per(10)
  end

  def show
    @availabilities = @property.availabilities
                               .order(scheduled_date: :asc)
                               .page(params[:page])
                               .per(5)

    if params["future_only"] == "1"
      @availabilities = @availabilities.future
    end

    @grouped_availabilities = @availabilities.group_by { |a| a.scheduled_date.to_fs(:basic_date) }
  end

  def new
    @property = Property.new
  end

  def edit
  end

  def create
    @property = Property.new(property_params)

    if @property.save
      flash[:notice] = "Property successfully created."
      redirect_to property_path(@property)
    else
      flash[:error] = "Failed to create property."
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @property.update(property_params)
      flash[:notice] = "Property successfully updated."
      redirect_to property_path(@property)
    else
      flash[:error] = "Failed to edit property."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @property.destroy
    flash[:notice] = "Property successfully destroyed."
    redirect_to properties_path
  end

  private

  def find_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:name, :description, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/availabilities/_card.html.haml
= link_to property_availability_path(property, availability), class: "availability-card" do
  .scheduled-date
    = availability.scheduled_date.to_fs(:basic_time)
  .manager-name
    %span Managed by:
    = availability.manager_name

app/views/availabilities/_form.html.haml
= render "shared/error_message", errors: availability.errors

= form_with model: availability, url: path, class: "form" do |form|
  .form-group
    = form.label :manager_name
    = form.text_field :manager_name, required: true

    .form-group
    = form.label :scheduled_date
    = form.datetime_local_field :scheduled_date, required: true

  .form-group
    = form.submit "Submit", class: "button"

app/views/availabilities/edit.html.haml
%h1
  Editing Availability for:
  = link_to " #{@property.name}", property_path(@property)

= render "form", availability: @availability, path: property_availability_path(@property, @availability)

app/views/availabilities/new.html.haml
%h1
  New availability for:
  = link_to " #{@property.name}", property_path(@property)

= render "form", availability: @availability, path: property_availabilities_path

app/views/availabilities/show.html.haml
%article.article
  %section.section
    = render "properties/details", property: @property, show_actions: true

%article.article
  %section.section
    .availability
      %p.book-for Bookings For:
      .datetime= @availability.scheduled_date.to_fs(:full_readable)
      .actions
        - if @availability.bookable?
          = link_to "Book this Timeslot", new_availability_booking_path(@availability), class: "button"
        = link_to "Edit", edit_property_availability_path(@property, @availability), class: "button"
        = link_to "Destroy", property_availability_path(@property, @availability), class: "button -red", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this availability?" }
  %section.section
    .booking-list
      - @bookings.each do |booking|
        = render "bookings/card", booking: booking, availability: @availability

app/views/bookings/_card.html.haml
.booking-card
  .tenant-name
    = booking.potential_tenant_name
  .actions
    = link_to "Edit", edit_availability_booking_path(availability, booking), class: "button"
    = link_to "Destroy", availability_booking_path(availability, booking), class: "button -red", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?" }

app/views/bookings/_form.html.haml
= render "shared/error_message", errors: booking.errors

= form_with model: booking, url: path, class: "form" do |form|
  .form-group
    = form.label :potential_tenant_name, "Please enter your name"
    = form.text_field :potential_tenant_name, required: true

  .form-group
    = form.submit "Submit", class: "button"

app/views/bookings/edit.html.haml
%article.article
  %section.section
    .section-header
      You editing the Booking for:
      = @availability.scheduled_date.to_fs(:full_readable)

  %section.section
    = render "form", booking: @booking, path: availability_booking_path(@availability, @booking)

app/views/bookings/new.html.haml
%article.article
  %section.section
    .section-header You are Booking
    = render "properties/details", property: @property, show_actions: false

  %section.section
    .section-header
      For the timeslot of:
      = @availability.scheduled_date.to_fs(:full_readable)

  %section.section
    = render "form", booking: @booking, path: availability_bookings_path(@availability)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Tech Test"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    %link{href: "https://fonts.googleapis.com", rel: "preconnect"}/
    %link{crossorigin: "", href: "https://fonts.gstatic.com", rel: "preconnect"}/
    %link{href: "https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap", rel: "stylesheet"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .container
      = render "shared/nav"
      = render "shared/flash"
      .main
        = yield

app/views/properties/_details.html.haml
.property
  %h1.name= link_to property.name, property_path(property)
  %p.address= property.address
  %p.description= property.description

  - if show_actions
    .actions
      = link_to "New Availability", new_property_availability_path(property), class: "button"
      = link_to "Edit", edit_property_path(property), class: "button"
      = link_to "Destroy", property_path(property), class: "button -red", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this property?" }

app/views/properties/_form.html.haml
= render "shared/error_message", errors: property.errors

= form_with model: property, class: "form" do |form|
  .form-group
    = form.label :name
    = form.text_field :name, required: true

  .form-group
    = form.label :description
    = form.textarea :description

  .form-group
    = form.label :address
    = form.text_field :address, required: true

  .form-group
    = form.submit "Submit", class: "button"

app/views/properties/edit.html.haml
%h1
  Editing:
  = link_to " #{@property.name}", property_path(@property)

= render "form", property: @property

app/views/properties/index.html.haml
%div
  = link_to "New Property", new_property_path, class: "button"
.property-list
  - @properties.each do |property|
    = link_to property, class: "property-card" do
      .details
        %h1.name= property.name
        %span.address= property.address
        %p.description= truncate(property.description, length: 150)
        %p.availabilities
          = property.availabilities.future.count
          Available timeslots

= paginate @properties

app/views/properties/new.html.haml
%h1 New Property
= render "form", property: @property

app/views/properties/show.html.haml
- bool_future_only = params["future_only"] == "1"
- show_future_params = bool_future_only ? "0" : "1"
- show_future_text = bool_future_only ? "Show All" : "Only Future Timeslots"

= render "properties/details", property: @property, show_actions: true

.availabilities
  %h2 Available Timeslots
  .actions
    = link_to show_future_text, property_path(@property, future_only: show_future_params), class: "button"
  - @grouped_availabilities.each do |date, availabilities|
    .availability-list
      .day
        = date.to_datetime.to_fs(:basic_date)
      - availabilities.each do |availability|
        = render "availabilities/card", availability: availability, property: @property
  = paginate @availabilities

app/views/shared/_error_message.html.haml
.error-message
  = errors.full_messages.to_sentence

app/views/shared/_flash.html.haml
- if flash[:notice]
  .flash.-notice
    = flash[:notice]

- if flash[:error]
  .flash.-error
    = flash[:error]

app/views/shared/_nav.html.haml
%nav.main-nav
  = link_to "Home", root_path, class: "link"